completion:
	for i in myapp mysimpleapp pcorelist subrepo nometa ; do \
		appspec completion examples/$$i-spec.yaml --zsh  > examples/zsh/_$$i; \
		appspec completion examples/$$i-spec.yaml --bash > examples/bash/$$i.bash; \
	done

pod:
	for i in myapp mysimpleapp pcorelist subrepo nometa ; do \
		appspec pod examples/$$i-spec.yaml > examples/pod/$$i.pod; \
	done

html:
	for i in myapp mysimpleapp pcorelist subrepo nometa ; do \
		pod2html examples/pod/$$i.pod | perl -plE's/mailto:.*(?=")/mailto:/' > examples/html/$$i.html; \
	done

update: completion pod html

cover:
	HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,local,+ignore,^t/,+ignore,^xt/" prove -lr t xt
	cover

process-pod:
	./utils/process-pod.pl

# https://leanpub.com/the-tao-of-tmux/read/
watch-test:
	(find t/ xt/ -name "*.t"; \
	find lib/ -name "*.pm"; \
	find examples/ share/ -name "*.yaml" \
	) | entr -c prove -lr t xt
