---
type: object
required: [name, appspec]
properties:
  name: { type: string }
  appspec:
    type: object
    required: [version]
    additionalProperties: false
    properties:
      version: { type: number }
  title: { type: string }
  abstract: { type: string }
  description: { type: string }
  options:
    '$ref': '#/definitions/options'
  subcommands:
    type: object
    additionalProperties: false
    patternProperties:
      "^[a-zA-Z0-9_]+$":
        '$ref': '#/definitions/command'
definitions:
  optionTypeSimple:
    enum: [flag, string]
  optionTypeEnum:
    additionalProperties: false
    type: object
    properties:
      enum:
        type: array
  options:
    type: array
    items:
      '$ref': '#/definitions/option'
  option:
    type: object
    additionalProperties: false
    required: [name]
    properties:
      name: { type: string }
      summary: { type: string }
      description: { type: string }
      multiple: { '$ref': '#/definitions/bool' }
      type:
        oneOf:
          - '$ref': '#/definitions/optionTypeSimple'
          - '$ref': '#/definitions/optionTypeEnum'
      aliases:
        type: array
        items: { type: string }
      required: { '$ref': '#/definitions/bool' }
      completion:
        type: object
  command:
    type: object
    additionalProperties: false
    properties:
      summary: { type: string }
      description: { type: string }
      op: { type: string }
      parameters:
        type: array
        additionalProperties: false
        properties:
          name: { type: string }
          required: { '$ref': '#/definitions/bool' }
          type: { type: object }
      options: { '$ref': '#/definitions/options' }
      subcommands:
        type: object
        additionalProperties: false
        patternProperties:
          "^[a-zA-Z0-9_]+$":
            '$ref': '#/definitions/command'
  bool:
    oneOf:
      - { type: boolean }
      - { type: integer }
