=head1 NAME

myapp - My Very Cool App

=head1 ABSTRACT

This app can do very cool things

=head1 DESCRIPTION

This is a very useful description for myapp.
This is a very useful description for myapp.
This is a very useful description for myapp.
This is a very useful description for myapp.


=head2 GLOBAL OPTIONS

    --verbose -v    be verbose (flag)       
    --help -h       Show command help (flag)


=head2 SUBCOMMANDS

=head3  convert

    myapp  convert <type> <source> <value> <target>+

Various unit conversions

Parameters:

    type    *    The type of unit to convert    
    source  *    The source unit to convert from
    value   *    The value to convert           
    target  * [] The target unit (multiple)     

=head3  cook

    myapp  cook [options] <drink>

Cook something

Options:

    --with        Drink with ...  
    --sugar -s    add sugar (flag)

Parameters:

    drink  *  What to drink

=head3  palindrome

    myapp  palindrome <string>

Check if a string is a palindrome

Parameters:

    string  *  

=head3  weather

    myapp  weather <subcommands>

Weather


=head3 weather cities

    myapp weather cities [options]

show list of cities

Options:

    --country -c   [] country name(s) (multiple)


=head3 weather countries

    myapp weather countries

show list of countries


=head3 weather show

    myapp weather show [options] <country> <city>+

Show Weather forecast

Options:

    --temperature -T    show temperature (flag)              
    --celsius -C        show temperature in celsius (flag)   
    --fahrenheit -F     show temperature in fahrenheit (flag)

Parameters:

    country  *    Specify country                  
    city     * [] Specify city or cities (multiple)

=head3  help

    myapp  help <subcommands> [options]

Show command help

Options:

    --all     (flag)


=head3  _complete

    myapp  _complete [options]

Generate self completion

Options:

    --name    name of the program
    --zsh     for zsh (flag)     
    --bash    for bash (flag)    




