name: linux

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ '*' ]

jobs:

  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
        - '5.12-buster'
        - '5.14-buster'
        - '5.16-buster'
        - '5.18-buster'
        - '5.20-buster'
        - '5.22-buster'
        - '5.24-buster'
        - '5.26-buster'
        - '5.28-buster'
        - '5.30-bullseye'
        - '5.32-bullseye'
        - '5.34-bullseye'
        - '5.36-bookworm'
        - '5.38-bookworm'
        - 'latest'

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
    - uses: actions/checkout@v3
    - run: env | sort
    - run: perl -V
    - name: Install deps
      run: >
        cpanm --quiet --notest
        Test::Deep List::MoreUtils YAML::PP Text::Table Ref::Util Moo
        Module::Runtime List::Util
    - name: Run Tests
      run: prove -lr t

